### ISSUE TITLE
💫 Build social links only with username

### ISSUE THREAD

**Issue by Airscripts** [ptkdev/aboutmeinfo-telegram-bot#6]
### Feature description

I'd like to insert only my username such as airscript or @airscript in order to set my social on about me.

### Feature motivation

The reason behind this request is that with this feature, the users will just add their username instead of the entire link and it would be more accessibile and easy to use.

**Comment by ptkdev** [comment]
Coming soon...

**Comment by ptkdev** [comment]
Available in `v0.6.4`
